name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: download missing files
      run: |
       cd ./app/src/main/assets
       wget -O imagefs.txz https://github.com/TGP-17/winlator/raw/refs/heads/longyunju2-glibc/app/src/main/assets/imagefs.txz
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y libgl1 libglu1-mesa libc6 lib32z1
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
       name: Winlator APK
       path: app/build/outputs/apk/debug/app-debug.apk
